from flask import *
import random

app = Flask(__name__)

@app.route('/random/feeling', methods=['GET'])
def randomFeeling():
    feelings = [
        'happiness',
        'love',
        'relief',
        'contentment',
        'amusement',
        'joy',
        'pride',
        'excitement',
        'peace',
        'satisfaction',
        'compassion',
        'lonely',
        'heartbroken',
        'gloomy',
        'disappointed',
        'hopeless',
        'grieved',
        'unhappy',
        'lost',
        'troubled',
        'resigned',
        'miserable',
        'worried',
        'doubtful',
        'nervous',
        'anxious',
        'terrified',
        'panicked',
        'horrified',
        'desperate',
        'confused',
        'stressed',
        'annoyed',
        'frustrated',
        'peeved',
        'contrary',
        'bitter',
        'infuriated',
        'irritated',
        'mad',
        'cheated',
        'vengeful',
        'insulted',
        'dislike',
        'revulsion',
        'loathing',
        'disapproving',
        'offended',
        'horrified',
        'uncomfortable',
        'nauseated',
        'disturbed',
        'withdrawal',
        'aversion',
    ]
    return random.choice(feelings)

@app.route('/random/postfeeling', methods=['POST'])
def randomFeelingPOST():
    feelings = [
        'happiness',
        'love',
        'relief',
        'contentment',
        'amusement',
        'joy',
        'pride',
        'excitement',
        'peace',
        'satisfaction',
        'compassion',
        'lonely',
        'heartbroken',
        'gloomy',
        'disappointed',
        'hopeless',
        'grieved',
        'unhappy',
        'lost',
        'troubled',
        'resigned',
        'miserable',
        'worried',
        'doubtful',
        'nervous',
        'anxious',
        'terrified',
        'panicked',
        'horrified',
        'desperate',
        'confused',
        'stressed',
        'annoyed',
        'frustrated',
        'peeved',
        'contrary',
        'bitter',
        'infuriated',
        'irritated',
        'mad',
        'cheated',
        'vengeful',
        'insulted',
        'dislike',
        'revulsion',
        'loathing',
        'disapproving',
        'offended',
        'horrified',
        'uncomfortable',
        'nauseated',
        'disturbed',
        'withdrawal',
        'aversion',
    ]
    return random.choice(feelings)

if __name__ == "__main__":
    app.run(debug=True)